name: ${project.name}
version: ${project.version}
author: DSH105
description: Harness the Destructive Power of Nature
website: ${project.url}
main: ${main.class}
commands:
    vupdate:
        description: Update the Vortex plugin.